# Generated by Django 4.1.1 on 2022-10-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmodel",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
