# Generated by Django 4.1.1 on 2022-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_recipe_directions_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
        ),
    ]
